# Generated by Django 5.0.8 on 2024-08-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('post_date', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('likes', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='api/posts/')),
            ],
        ),
        migrations.CreateModel(
            name='MyModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
