# Generated by Django 5.0.8 on 2024-08-16 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_user_delete_project_remove_community_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='community',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
