# Generated by Django 5.0.8 on 2024-08-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImg',
            field=models.ImageField(null=True, upload_to='api/posts/'),
        ),
    ]
