# Generated by Django 5.0.8 on 2024-08-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_posts_alter_post_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='api.post'),
        ),
    ]
