# Generated by Django 5.0.8 on 2024-08-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='api/profiles/'),
        ),
    ]
