# Generated by Django 5.0.8 on 2024-09-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_like_post_like_post_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
